'use strict';
let start = 'hello';
let a = 'owu';
let b = 'com';
let c = 'ua';
let first = 1;
let ten = 10;
let nine = -999;
let count = 123;
const PI = 3.14;
let num = 2.7;
let age = 16;
let x = age > num;
let y = age < num;
console.log(start);
console.log(a);
console.log(b);
console.log(c);
console.log(first);
console.log(ten);
console.log(nine);
console.log(count);
console.log(PI);
console.log(num);
console.log(age);
console.log(x);
console.log(y);
let firstName = 'Kateryna';
let middleName = 'Shelest';
let lastName = 'Olehivna';
let persone = `${middleName} ${firstName} ${lastName}`;
console.log(persone);
let v = 100;
let n = '100';
let k = true;
console.log(typeof v);
console.log(typeof n);
console.log(typeof k);


